name: Elixir CI

on: push

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.10.4'
        otp-version: '23.3.4.5'
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install mix dependencies
      run: mix deps.get
    - name: Check code format
      run: mix format --check-formatted
    - name: Install yarn dependencies
      run: yarn --cwd assets
    - name: Compile assets
      run: cd assets && ./node_modules/.bin/webpack --mode development
    - name: Compile elixir
      run: MIX_ENV=test mix compile --force --warnings-as-errors
    - name: Run tests
      run: mix test
